### ISSUE TITLE
USER STORY: Create and setup initial workspace

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages#1]
As a **Developer** I can **create a developing workspace** so that **I can start building the frontend**

## Acceptance Criteria
* Create a Gitpod workspace environment for the frontend project
* Use React template from Code Institute
* Use correct version of bootstrap

## Tasks
- [ ]  Task 1 – Create a project in Github call kkimages as an exmaple
- [ ]  Task 2 – Launch Github and install React template from Code Institute as follow:
'npx create-react-app . --template git+https://github.com/Code-Institute-Org/cra-template-moments.git --use-npm'
- [ ]  Task 3 – Install Gitpod extension ES7 React/Redux/GraphQl/React-Native
- [ ]  Task 4 – Install Gitpod extension Prettier - (Code formatter)
- [ ]  Task 5 – Install bootstrap 'npm install react-bootstrap@1.6.3 bootstrap@4.6.0'
