### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages#21]
As a **User** I can **view a nav bar from every page** so that **I can navigate easily between pages**

## Acceptance Criteria 1
**Given** that the site has several url pages
**When** user want to navigate the site
**Then** it will be helpful to have a navigation bar

## Tasks
- [ ] Task 1 – Create a navigation bar on to of the site
- [ ] Task 2 – Collapse the navigation bar to menu bar on smaller devices
- [ ] Task 3 –  Add appropriate navigation menu item

## EPIC
1. #20
