### ISSUE TITLE
USER STORY: Popular albums

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages#27]
As a **Registered User** I can **see a list of the most liked albums** so that ** I can see which albums are popular**

## Acceptance Criteria 1
**Given** that there are popular albums
**When** we want to tell the user
**Then** it should shows as a sidebar item

## Tasks
- [ ] Task 1 – Count the likes in each album
- [ ] Task 2 – Fetch the top 5 albums that has must likes
- [ ] Task 3 – Display these albums as a list

## EPIC
1. #24
