### ISSUE TITLE
USER STORY: Edit and Delete Photos

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages#37]
As a **Owner** I can **delete photos from the album** so that **the photos are no longer available on the app**

## Acceptance Criteria 1
**Given** that I am the owner of the album
**When** I want to edit or remove photos
**Then** it allows me to update or delete photos

## Tasks
- [ ] Task 1 – Check credential
- [ ] Task 2 – Create Edit button for the post
- [ ] Task 3 – Create Delete button for the post

## EPIC
1. #34
